// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package db

import (
	"context"
)

const createRoomConfig = `-- name: CreateRoomConfig :exec
INSERT INTO room_config (session_id, top_marquee_enabled, bottom_marquee_enabled, top_marquee_label, bottom_marquee_label, top_marquee_source, bottom_marquee_source, current_index)
VALUES (?, 0, 0, '', '', 'current', 'current', 0)
`

func (q *Queries) CreateRoomConfig(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, createRoomConfig, sessionID)
	return err
}

const getCurrentIndex = `-- name: GetCurrentIndex :one
SELECT current_index FROM room_config WHERE session_id = ?
`

func (q *Queries) GetCurrentIndex(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCurrentIndex, sessionID)
	var current_index int64
	err := row.Scan(&current_index)
	return current_index, err
}

const getRoomConfig = `-- name: GetRoomConfig :one
SELECT session_id, top_marquee_enabled, bottom_marquee_enabled, top_marquee_label, bottom_marquee_label, top_marquee_source, bottom_marquee_source, current_index
FROM room_config
WHERE session_id = ?
`

func (q *Queries) GetRoomConfig(ctx context.Context, sessionID string) (RoomConfig, error) {
	row := q.db.QueryRowContext(ctx, getRoomConfig, sessionID)
	var i RoomConfig
	err := row.Scan(
		&i.SessionID,
		&i.TopMarqueeEnabled,
		&i.BottomMarqueeEnabled,
		&i.TopMarqueeLabel,
		&i.BottomMarqueeLabel,
		&i.TopMarqueeSource,
		&i.BottomMarqueeSource,
		&i.CurrentIndex,
	)
	return i, err
}

const updateCurrentIndex = `-- name: UpdateCurrentIndex :exec
UPDATE room_config SET current_index = ? WHERE session_id = ?
`

type UpdateCurrentIndexParams struct {
	CurrentIndex int64
	SessionID    string
}

func (q *Queries) UpdateCurrentIndex(ctx context.Context, arg UpdateCurrentIndexParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrentIndex, arg.CurrentIndex, arg.SessionID)
	return err
}

const updateRoomConfig = `-- name: UpdateRoomConfig :exec
UPDATE room_config
SET top_marquee_enabled = ?,
    bottom_marquee_enabled = ?,
    top_marquee_label = ?,
    bottom_marquee_label = ?,
    top_marquee_source = ?,
    bottom_marquee_source = ?
WHERE session_id = ?
`

type UpdateRoomConfigParams struct {
	TopMarqueeEnabled    int64
	BottomMarqueeEnabled int64
	TopMarqueeLabel      string
	BottomMarqueeLabel   string
	TopMarqueeSource     string
	BottomMarqueeSource  string
	SessionID            string
}

func (q *Queries) UpdateRoomConfig(ctx context.Context, arg UpdateRoomConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomConfig,
		arg.TopMarqueeEnabled,
		arg.BottomMarqueeEnabled,
		arg.TopMarqueeLabel,
		arg.BottomMarqueeLabel,
		arg.TopMarqueeSource,
		arg.BottomMarqueeSource,
		arg.SessionID,
	)
	return err
}
