// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type QueueItem struct {
	ID             string
	SessionID      string
	YoutubeVideoID string
	YoutubeUrl     string
	MarqueeText    string
	Position       int64
	AddedAt        time.Time
}

type RoomConfig struct {
	SessionID            string
	TopMarqueeEnabled    int64
	BottomMarqueeEnabled int64
	TopMarqueeLabel      string
	BottomMarqueeLabel   string
	TopMarqueeSource     string
	BottomMarqueeSource  string
	CurrentIndex         int64
}

type Session struct {
	ID            string
	FriendJoinKey string
	ViewerToken   string
	CreatedAt     time.Time
}
