// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queue.sql

package db

import (
	"context"
)

const addQueueItem = `-- name: AddQueueItem :exec
INSERT INTO queue_items (id, session_id, youtube_video_id, youtube_url, marquee_text, position, added_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
`

type AddQueueItemParams struct {
	ID             string
	SessionID      string
	YoutubeVideoID string
	YoutubeUrl     string
	MarqueeText    string
	Position       int64
}

func (q *Queries) AddQueueItem(ctx context.Context, arg AddQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, addQueueItem,
		arg.ID,
		arg.SessionID,
		arg.YoutubeVideoID,
		arg.YoutubeUrl,
		arg.MarqueeText,
		arg.Position,
	)
	return err
}

const deleteQueueItem = `-- name: DeleteQueueItem :exec
DELETE FROM queue_items WHERE id = ? AND session_id = ?
`

type DeleteQueueItemParams struct {
	ID        string
	SessionID string
}

func (q *Queries) DeleteQueueItem(ctx context.Context, arg DeleteQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteQueueItem, arg.ID, arg.SessionID)
	return err
}

const getQueueItem = `-- name: GetQueueItem :one
SELECT id, session_id, youtube_video_id, youtube_url, marquee_text, position, added_at
FROM queue_items
WHERE id = ? AND session_id = ?
`

type GetQueueItemParams struct {
	ID        string
	SessionID string
}

func (q *Queries) GetQueueItem(ctx context.Context, arg GetQueueItemParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, getQueueItem, arg.ID, arg.SessionID)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.YoutubeVideoID,
		&i.YoutubeUrl,
		&i.MarqueeText,
		&i.Position,
		&i.AddedAt,
	)
	return i, err
}

const getQueueItemAtPosition = `-- name: GetQueueItemAtPosition :one
SELECT id, session_id, youtube_video_id, youtube_url, marquee_text, position, added_at
FROM queue_items
WHERE session_id = ? AND position = ?
`

type GetQueueItemAtPositionParams struct {
	SessionID string
	Position  int64
}

func (q *Queries) GetQueueItemAtPosition(ctx context.Context, arg GetQueueItemAtPositionParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, getQueueItemAtPosition, arg.SessionID, arg.Position)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.YoutubeVideoID,
		&i.YoutubeUrl,
		&i.MarqueeText,
		&i.Position,
		&i.AddedAt,
	)
	return i, err
}

const getQueueItemCount = `-- name: GetQueueItemCount :one
SELECT COUNT(*) FROM queue_items WHERE session_id = ?
`

func (q *Queries) GetQueueItemCount(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getQueueItemCount, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getQueueItems = `-- name: GetQueueItems :many
SELECT id, session_id, youtube_video_id, youtube_url, marquee_text, position, added_at
FROM queue_items
WHERE session_id = ?
ORDER BY position ASC
`

func (q *Queries) GetQueueItems(ctx context.Context, sessionID string) ([]QueueItem, error) {
	rows, err := q.db.QueryContext(ctx, getQueueItems, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueItem
	for rows.Next() {
		var i QueueItem
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.YoutubeVideoID,
			&i.YoutubeUrl,
			&i.MarqueeText,
			&i.Position,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQueueItemMarqueeText = `-- name: UpdateQueueItemMarqueeText :exec
UPDATE queue_items SET marquee_text = ? WHERE id = ?
`

type UpdateQueueItemMarqueeTextParams struct {
	MarqueeText string
	ID          string
}

func (q *Queries) UpdateQueueItemMarqueeText(ctx context.Context, arg UpdateQueueItemMarqueeTextParams) error {
	_, err := q.db.ExecContext(ctx, updateQueueItemMarqueeText, arg.MarqueeText, arg.ID)
	return err
}

const updateQueueItemPosition = `-- name: UpdateQueueItemPosition :exec
UPDATE queue_items SET position = ? WHERE id = ? AND session_id = ?
`

type UpdateQueueItemPositionParams struct {
	Position  int64
	ID        string
	SessionID string
}

func (q *Queries) UpdateQueueItemPosition(ctx context.Context, arg UpdateQueueItemPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateQueueItemPosition, arg.Position, arg.ID, arg.SessionID)
	return err
}
