// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, friend_join_key, viewer_token, created_at)
VALUES (?, ?, ?, datetime('now'))
`

type CreateSessionParams struct {
	ID            string
	FriendJoinKey string
	ViewerToken   string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.FriendJoinKey, arg.ViewerToken)
	return err
}

const friendKeyExists = `-- name: FriendKeyExists :one
SELECT COUNT(*) > 0 AS key_exists
FROM sessions
WHERE LOWER(friend_join_key) = LOWER(?)
`

func (q *Queries) FriendKeyExists(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRowContext(ctx, friendKeyExists, lower)
	var key_exists bool
	err := row.Scan(&key_exists)
	return key_exists, err
}

const getSession = `-- name: GetSession :one
SELECT id, friend_join_key, viewer_token, created_at
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.FriendJoinKey,
		&i.ViewerToken,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByFriendKey = `-- name: GetSessionByFriendKey :one
SELECT id, friend_join_key, viewer_token, created_at
FROM sessions
WHERE LOWER(friend_join_key) = LOWER(?)
`

func (q *Queries) GetSessionByFriendKey(ctx context.Context, lower string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByFriendKey, lower)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.FriendJoinKey,
		&i.ViewerToken,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByViewerToken = `-- name: GetSessionByViewerToken :one
SELECT id, friend_join_key, viewer_token, created_at
FROM sessions
WHERE viewer_token = ?
`

func (q *Queries) GetSessionByViewerToken(ctx context.Context, viewerToken string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByViewerToken, viewerToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.FriendJoinKey,
		&i.ViewerToken,
		&i.CreatedAt,
	)
	return i, err
}
